"""
BibTeX Exporter für Academic Agent v2.3+

Exportiert Papers als BibTeX-Einträge für LaTeX.

Usage:
    from src.export.bibtex_exporter import export_bibtex

    export_bibtex(papers, output_path=Path("bibliography.bib"))
"""

import json
import re
from pathlib import Path
from typing import List, Dict, Any


def sanitize_bibtex_key(doi: str, title: str, year: int) -> str:
    """Generate BibTeX key from metadata"""
    # Use first author last name + year if possible
    # Fallback: sanitized DOI or title
    if doi:
        key = doi.replace("/", "_").replace(".", "_")
    else:
        key = re.sub(r'[^a-zA-Z0-9]', '_', title[:20])

    return f"{key}_{year}"


def export_bibtex(papers: List[Dict[str, Any]], output_path: Path) -> None:
    """
    Export papers as BibTeX entries

    Args:
        papers: List of paper dicts with metadata
        output_path: Output .bib file path
    """
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("% Bibliography - Generated by Academic Agent v2.3+\n\n")

        for paper in papers:
            # Generate BibTeX key
            key = sanitize_bibtex_key(
                paper.get('doi', ''),
                paper.get('title', ''),
                paper.get('year', 2024)
            )

            # Determine entry type
            entry_type = "article"  # Most papers are articles

            # Write entry
            f.write(f"@{entry_type}{{{key},\n")

            # Title
            if paper.get('title'):
                f.write(f"  title = {{{paper['title']}}},\n")

            # Authors
            if paper.get('authors'):
                authors = " and ".join(paper['authors'])
                f.write(f"  author = {{{authors}}},\n")

            # Year
            if paper.get('year'):
                f.write(f"  year = {{{paper['year']}}},\n")

            # Journal/Conference
            if paper.get('venue'):
                f.write(f"  journal = {{{paper['venue']}}},\n")

            # Volume
            if paper.get('volume'):
                f.write(f"  volume = {{{paper['volume']}}},\n")

            # Issue/Number
            if paper.get('issue'):
                f.write(f"  number = {{{paper['issue']}}},\n")

            # Pages
            if paper.get('pages'):
                f.write(f"  pages = {{{paper['pages']}}},\n")

            # DOI
            if paper.get('doi'):
                f.write(f"  doi = {{{paper['doi']}}},\n")

            # URL
            if paper.get('url'):
                f.write(f"  url = {{{paper['url']}}},\n")

            f.write("}\n\n")

    print(f"✅ Exported {len(papers)} papers to {output_path}")


# CLI
def main():
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="BibTeX Exporter")
    parser.add_argument('--papers', help='Input JSON papers file')
    parser.add_argument('--output', help='Output .bib file')
    parser.add_argument('--test', action='store_true', help='Run test')

    args = parser.parse_args()

    if args.test:
        test_papers = [
            {
                "doi": "10.1109/ICSE.2023.00042",
                "title": "DevOps Governance Framework",
                "authors": ["Smith, John", "Doe, Alice"],
                "year": 2024,
                "venue": "IEEE Software",
                "volume": "41",
                "issue": "2",
                "pages": "45-52"
            }
        ]

        output_path = Path("test_bibliography.bib")
        export_bibtex(test_papers, output_path)

        print(f"\n📄 BibTeX Preview:")
        print(output_path.read_text())

        output_path.unlink()
        print("\n✅ BibTeX Exporter test passed!")
        sys.exit(0)

    if not args.papers or not args.output:
        parser.error("--papers and --output required (unless --test)")

    try:
        with open(args.papers, 'r') as f:
            data = json.load(f)
            papers = data.get('papers', data) if isinstance(data, dict) else data

        export_bibtex(papers, Path(args.output))

    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
